quiet: False
disable-version-string: True
with-expecter: True
mockname: "{{.InterfaceName}}"
filename: "{{.InterfaceName | lower}}_mock.go"
outpkg: mocks
packages:
  github.com/tech-challenge-fiap-5soat/tc-ff-kitchen-api/src/common/interfaces:
    config:
      dir: "test/mocks"
      mockname: "Mock{{.InterfaceName}}"
    interfaces:
      DataSource:
      OrderGateway:
      OrderUseCase:
      OrderApi:
      DatabaseSource: