// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockPublisherGateway is an autogenerated mock type for the PublisherGateway type
type MockPublisherGateway struct {
	mock.Mock
}

type MockPublisherGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublisherGateway) EXPECT() *MockPublisherGateway_Expecter {
	return &MockPublisherGateway_Expecter{mock: &_m.Mock}
}

// GetQueueUrl provides a mock function with given fields:
func (_m *MockPublisherGateway) GetQueueUrl() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetQueueUrl")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockPublisherGateway_GetQueueUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueueUrl'
type MockPublisherGateway_GetQueueUrl_Call struct {
	*mock.Call
}

// GetQueueUrl is a helper method to define mock.On call
func (_e *MockPublisherGateway_Expecter) GetQueueUrl() *MockPublisherGateway_GetQueueUrl_Call {
	return &MockPublisherGateway_GetQueueUrl_Call{Call: _e.mock.On("GetQueueUrl")}
}

func (_c *MockPublisherGateway_GetQueueUrl_Call) Run(run func()) *MockPublisherGateway_GetQueueUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPublisherGateway_GetQueueUrl_Call) Return(_a0 string) *MockPublisherGateway_GetQueueUrl_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPublisherGateway_GetQueueUrl_Call) RunAndReturn(run func() string) *MockPublisherGateway_GetQueueUrl_Call {
	_c.Call.Return(run)
	return _c
}

// PublishMessage provides a mock function with given fields: queueName, message
func (_m *MockPublisherGateway) PublishMessage(queueName string, message string) error {
	ret := _m.Called(queueName, message)

	if len(ret) == 0 {
		panic("no return value specified for PublishMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(queueName, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPublisherGateway_PublishMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishMessage'
type MockPublisherGateway_PublishMessage_Call struct {
	*mock.Call
}

// PublishMessage is a helper method to define mock.On call
//   - queueName string
//   - message string
func (_e *MockPublisherGateway_Expecter) PublishMessage(queueName interface{}, message interface{}) *MockPublisherGateway_PublishMessage_Call {
	return &MockPublisherGateway_PublishMessage_Call{Call: _e.mock.On("PublishMessage", queueName, message)}
}

func (_c *MockPublisherGateway_PublishMessage_Call) Run(run func(queueName string, message string)) *MockPublisherGateway_PublishMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockPublisherGateway_PublishMessage_Call) Return(_a0 error) *MockPublisherGateway_PublishMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPublisherGateway_PublishMessage_Call) RunAndReturn(run func(string, string) error) *MockPublisherGateway_PublishMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPublisherGateway creates a new instance of MockPublisherGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublisherGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublisherGateway {
	mock := &MockPublisherGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
